### PR TITLE
Log scale required bug

### PR DESCRIPTION
**Pull request by MauriceHendrix**
This PR makes the log scale no longer required

### CODE REVIEW

**Review by flawmop — COMMENTED** [review]
This is an improvement in that it'll allow the simulation to run, but the UI is still showing the simulation results in the (Δ APD90 vs.) Conc results on a log scale, so I'll hold off from approving because perhaps the presence of that checkbox is to show the simulation results concs on non-log scale if log scale is not selected.

**Comment by MauriceHendrix** [comment]
> This is an improvement in that it'll allow the simulation to run, but the UI is still showing the simulation results in the (Δ APD90 vs.) Conc results on a log scale, so I'll hold off from approving because perhaps the presence of that checkbox is to show the simulation results concs on non-log scale if log scale is not selected.

I thought that was just a parameter to be sullied to APpredict?  @mirams ?

**Comment by flawmop** [comment]
> @flawmop made some changes to only use logscale for the display if log scale was selected.

I wasn't sure whether this was the expected output so was interested to know what Gary thought about it.

I've tested your changes and noticed that you've applied the changes to the Δ APD90 vs. Conc which works fine, but not the qNet vs. Conc it seems

**Review by flawmop — APPROVED** [review]
All seems to be working ok

**Pull request merged**
