### PR TITLE
Changed to only create admin account if it doesn't exist

### LINKED ISSUE #115: Django authn mechanism issues
Things seems to be a bit unreliable with the Django authentication system

- If a password is reset using the "Reset Password" via email option, then the password is accepted only until the `ap-nimbus-client` container is restarted.
- If a user's email is updated using the `accounts/myaccount/` facility, they can't log in again until they've reset their password.

### PR DESCRIPTION
**Pull request by MauriceHendrix**
this should fix #115 I think, but it needs further testing: first whether it fixes @flawmop 's issues and if it does we need to check it does actually create the admin account if I change the account details in the env file to one that does not yet exist

### CODE REVIEW

**Review by flawmop — CHANGES_REQUESTED** [review]
- I think we need to drop the references to `DJANGO_SUPERUSER_USERNAME` because that's not in the documentation anywhere. 
- Can you also include an update to comments for `docker/env#DJANGO_SUPERUSER_PASSWORD` and `docker/env#DJANGO_SUPERUSER_INSTITUTION` to explain that these env vars will only be recognised if `DJANGO_SUPERUSER_EMAIL` does not already exist? Perhaps a link in the env file to client/accounts/management/commands/create_admin.py may suffice?
- I haven't been able to test the migration operation I don't think (I'm assuming this db migration is manipulating legacy database format data), otherwise it's working as expected.

**Comment by MauriceHendrix** [comment]
Aaah yes you're quite right so it wasn't a bug as such after all, just unclear in the instructions.

**Comment by flawmop** [comment]
I was hoping as part of this that you'd verify the presence of `DJANGO_SUPERUSER_USERNAME` in the following, because as far as I could see a user's full name is only requested on registration, it should never appear in the env vars (as it's not defined in `docker/env`), yet its presence in the code infers that it will potentially be found in environment vars.
- `client/files/migrations/0002_auto_20220105_1304.py`
- `client/accounts/management/commands/create_admin.py`

Also, the change you made to `docker/env` (i.e. "Please note that the password ...") isn't a comment

**Comment by MauriceHendrix** [comment]
> I was hoping as part of this that you'd verify the presence of `DJANGO_SUPERUSER_USERNAME` in the following, because as far as I could see a user's full name is only requested on registration, it should never appear in the env vars (as it's not defined in `docker/env`), yet its presence in the code infers that it will potentially be found in environment vars.
> 
> * `client/files/migrations/0002_auto_20220105_1304.py`
> * `client/accounts/management/commands/create_admin.py`
> 
> Also, the change you made to `docker/env` (i.e. "Please note that the password ...") isn't a comment

`DJANGO_SUPERUSER_USERNAME` could be added to the env file indeed.
I'll leave it up to you to update as you see fit and merge.

**Comment by flawmop** [comment]
Hi @MauriceHendrix, can you give the changes a quick lookover and let me know if there's anything you feel needs changing?

**Review by flawmop — APPROVED** [review]

**Comment by flawmop** [comment]
I've reinstated the option to assign an existing account as Django superuser for the extreme case of a superuser removing their own status accidentally!

**Pull request merged**
