### PR TITLE
ap-nimbus-client Release 2.0.0

### PR DESCRIPTION
**Pull request by kwabenantim**
* Supports https://github.com/CardiacModelling/ap-nimbus/issues/75

### CODE REVIEW

**Comment by kwabenantim** [comment]
## User Acceptance Testing
- [ ] Register
  - [ ] Internal
  - [ ] External
- [ ] Reset password
  - [ ] Internal
  - [ ] External
- [ ] Predefined models
  - [ ] Create and run simulations
  - [ ] View simulation results
- [ ] Upload model
  - [ ] Create and run simulations
  - [ ] View simulation results

**Comment by kwabenantim** [comment]
External emails are not being sent. Possibly site-specific.

**Comment by kwabenantim** [comment]
Simulations for all predefined CellML models run correctly.

**Comment by kwabenantim** [comment]
If an uploaded simulation fails, subsequent simulation runs start to fail (even for other models that were passing) until the app-manager is restarted.

**Review by mirams — APPROVED** [review]

**Pull request merged**
